# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7,7)
tensor

tensor([[0.9649, 0.4689, 0.8558, 0.3207, 0.9182, 0.2832, 0.5024],
        [0.8825, 0.4946, 0.3471, 0.1696, 0.9001, 0.1611, 0.9959],
        [0.2815, 0.2675, 0.5244, 0.9099, 0.1222, 0.3732, 0.0146],
        [0.4297, 0.7372, 0.1535, 0.3437, 0.3879, 0.6167, 0.4692],
        [0.2947, 0.6931, 0.6103, 0.6962, 0.4665, 0.7662, 0.9306],
        [0.9831, 0.2991, 0.0185, 0.1375, 0.8991, 0.6710, 0.4758],
        [0.9009, 0.2129, 0.1763, 0.4508, 0.4820, 0.3413, 0.7192]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
tensor2 = torch.rand(1,7)

# Perform matrix multiplication 
tensor.mul(tensor2)

tensor([[0.1967, 0.0250, 0.4941, 0.2082, 0.1579, 0.0192, 0.2674],
        [0.1799, 0.0263, 0.2004, 0.1101, 0.1548, 0.0109, 0.5300],
        [0.0574, 0.0142, 0.3028, 0.5907, 0.0210, 0.0253, 0.0077],
        [0.0876, 0.0392, 0.0886, 0.2231, 0.0667, 0.0418, 0.2497],
        [0.0601, 0.0369, 0.3523, 0.4520, 0.0802, 0.0519, 0.4952],
        [0.2004, 0.0159, 0.0107, 0.0893, 0.1546, 0.0454, 0.2532],
        [0.1836, 0.0113, 0.1018, 0.2927, 0.0829, 0.0231, 0.3827]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [9]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensorA = torch.rand(7,7)
tensorB = torch.rand(1,7)
# Matrix multiply tensors

tensorA.matmul(tensorB.T)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [10]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [19]:
# Set random seed


# Check for access to GPU
device = torch.device('mps' if torch.backends.mps.is_available() else 'cpu')
device

torch.mps.manual_seed(1234)


# Create two random tensors on GPU
tensorAA = torch.rand(2,3).to(device)
tensorBB = torch.rand(2,3).to(device)

t = tensorAA.matmul(tensorBB.T)

tensorAA, tensorBB, t



(tensor([[0.8579, 0.6870, 0.0051],
         [0.1757, 0.7497, 0.6047]], device='mps:0'),
 tensor([[0.1100, 0.2121, 0.9704],
         [0.8369, 0.2820, 0.3742]], device='mps:0'),
 tensor([[0.2450, 0.9136],
         [0.7650, 0.5846]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [20]:
# Perform matmul on tensor_A and tensor_B

t = tensorAA.matmul(tensorBB.T)


### 8. Find the maximum and minimum values of the output of 7.

In [21]:
# Find max
maxV = t.max()
# Find min
minV = t.min()

maxV, minV

(tensor(0.9136, device='mps:0'), tensor(0.2450, device='mps:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [24]:
# Find arg max

maxArg = t.argmax()


# Find arg min

minArg = t.argmin()


maxArg, minArg

(tensor(1, device='mps:0'), tensor(0, device='mps:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [25]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1,1,1,10)

# Remove single dimensions
tensorS = torch.squeeze(tensor)

# Print out tensors and their shapes
print(tensor, tensor.shape)
print(tensorS, tensorS.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
