# Introduciton to PyTorch 


## Lecture 01

The version of the pytorch

In [3]:
import torch 
torch.__version__

'2.5.1'

For scalar numbers we can use 

In [4]:
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)

tensor(7)
0


To get just the value we can 

In [6]:
scalar.item()

7

Also higher dimensions tensors 

In [10]:
vector = torch.tensor([7,2,3])
matrix = torch.tensor([[7,2,3],[3,2,7]])

print(vector)
print(matrix.ndim)


tensor([7, 2, 3])
2


Another useful property **.shape** meaning height and width of the tensor

In [11]:
matrix.shape 

torch.Size([2, 3])

In [35]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=3, out_features=6)

tensorA = torch.tensor([[1,2,3], [1,2,3]], dtype=torch.float32)
tensorB = torch.tensor([[7,8],[9,10],[11,12]])

output = linear(tensorA)

output



tensor([[0.7245, 0.7740, 1.6579, 0.8366, 1.1836, 1.4476],
        [0.7245, 0.7740, 1.6579, 0.8366, 1.1836, 1.4476]],
       grad_fn=<AddmmBackward0>)

In [68]:
x = torch.arange(0, 17 ,2)
y = x.view(1,9)
x = x.reshape(1,9)
z = torch.stack([x,y,x,y], dim=2)
x,y,z


(tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16]]),
 tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16]]),
 tensor([[[ 0,  0,  0,  0],
          [ 2,  2,  2,  2],
          [ 4,  4,  4,  4],
          [ 6,  6,  6,  6],
          [ 8,  8,  8,  8],
          [10, 10, 10, 10],
          [12, 12, 12, 12],
          [14, 14, 14, 14],
          [16, 16, 16, 16]]]))

In [71]:
torch.cuda.is_available()

False

In [74]:
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'mps'